### ISSUE TITLE
turning seeds to head

### ISSUE THREAD

**Issue by RIPISDRAD** [Sefiraat/Netheopoiesis#24]
Error Generated: 2022-09-10-23-37

Java Environment:
  Operating System: Linux
  Java Version: 17.0.4

Server Software: Paper
  Build: git-Paper-134 (MC: 1.19.2)
  Minecraft v1.19.2-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun vDEV - 1027 (git 96c873bd)
  Caused by: Netheopoiesis vDEV - 11 (git 57ce4103)

Installed Addons (57)
  + HardcoreSlimefun 1.0
  + EcoPower DEV - 5 (git 5c1ecd68)
  + DankTech2 DEV - 8 (git f2a8ab1f)
  + Netheopoiesis DEV - 11 (git 57ce4103)
  + MissileWarfare 1.6.16
  + SimpleStorage DEV - 10 (git ea5e5637)
  + GlobalWarming DEV - 11 (git 73ff77d4)
  + MiniBlocks DEV - 4 (git f7a34b6e)
  + SfChunkInfo DEV - 7 (git 30b6d0ef)
  + Bump Build 30 zh-CN(SlimefunGuguProject) (git 31e1bb3)
  + ExtraGear DEV - 13 (git c62047e2)
  + SFAdvancements DEV - 21 (git e6f6cf10)
  + SlimeHUD DEV - 7 (git fd655730)
  + SFCalc DEV - 37 (git dfc0fc41)
  + MobCapturer DEV - 21 (git f82c20fc)
  + TranscEndence DEV - 41 (git 98d7d47e)
  + AlchimiaVitae DEV - 22 (git 09618c12)
  + HotbarPets DEV - 38 (git fa6c871d)
  + SlimefunLuckyBlocks DEV - 36 (git 60f0c8dc)
  + ExoticGarden DEV - 78 (git 7f9a5f63)
  + HeadLimiter DEV - 14 (git 0a02e2fd)
  + Liquid DEV - 14 (git 0f5346bf)
  + SFMobDrops DEV - 6 (git d36aba47)
  + SoulJars DEV - 23 (git b8358a1f)
  + PotionExpansion DEV - 5 (git e2cfcd8a)
  + SlimyRepair DEV - 4 (git 790c41cb)
  + ExtraTools DEV - 36 (git 922c0324)
  + RelicsOfCthonia DEV - 6 (git 5ba8f971)
  + FoxyMachines DEV - 58 (git c2c2b8a7)
  + SlimefunOreChunks DEV - 15 (git 2520cb23)
  + SimpleMaterialGenerators DEV - 4 (git 5543cc8f)
  + DyeBench DEV - 5 (git ea20db26)
  + Supreme DEV - 11 (git 448154ef)
  + ElectricSpawners DEV - 23 (git 6ec96773)
  + Wildernether DEV - 5 (git 5be3da69)
  + CompressionCraft DEV - 23 (git 8a50d1d6)
  + VillagerUtil DEV - 1 (git 0a949b19)
  + ExtraHeads DEV - 23 (git 0b59a770)
  + SlimyTreeTaps DEV - 20 (git 963f0383)
  + FlowerPower DEV - 15 (git 35662ced)
  + PrivateStorage DEV - 18 (git 5832db21)
  + Galactifun DEV - 70 (git c69305ef)
  + FluffyMachines DEV - 126 (git cc67cc03)
  + DyedBackpacks DEV - 17 (git 8b329e96)
  + SoundMuffler DEV - 24 (git ae8e2bf7)
  + LiteXpansion DEV - 181 (git 79885526)
  + FNAmplifications DEV - 79 (git 220e6eb2)
  + ElementManipulation DEV - 25 (git dffbefdc)
  + InfinityExpansion DEV - 140 (git 0098d2fb)
  + Networks DEV - 44 (git 2e7bc54c)
  + DynaTech DEV - 170 (git a5e7b101)
  + SimpleUtils DEV - 15 (git 4250fd5e)
  + SlimefunWarfare DEV - 81 (git a3f393c8)
  + SlimeTinker DEV - 77 (git 99a520b9)
  + CrystamaeHistoria DEV - 78 (git 340f1a94)
  + SlimeCustomizer DEV - 27 (git 3d8b02e5)
  + EMCTech DEV - 3 (git bdc78e46)

Installed Plugins (87):
  + LuckyPanda DEV - 1 (git c8bd8dd7)
  + PlaceholderAPI 2.11.2
  + JoLe 1.1
  + ViaVersion 4.4.2
  + ViaBackwards 4.4.1
  + LuckPerms 5.4.41
  + VoidGen 2.2.1
  + OpenInv 4.2.1
  + ProtocolLib 5.0.0-SNAPSHOT-b600
  + LibsDisguises 10.0.31
  + Vault 1.7.3-b131
  + ViaRewind 2.0.2
  + Scoreboard-revision R4 1.1 RELEASE
  + SkinsRestorer 14.2.3
  + WorldEdit 7.2.12+6240-87f4ae1
  + Essentials 2.19.8-dev+2-b808511
  + AdvancedBan 2.3.0
  + TradeSystem 2.1.3
  + EssentialsChat 2.19.8-dev+2-b808511
  - TAB 3.1.2
  + WorldGuard 7.0.7+216b061
  + MythicMobs 5.1.4-3aa1b5d2
  + Slimefun DEV - 1027 (git 96c873bd)
  + HardcoreSlimefun 1.0
  + EcoPower DEV - 5 (git 5c1ecd68)
  + DankTech2 DEV - 8 (git f2a8ab1f)
  + Netheopoiesis DEV - 11 (git 57ce4103)
  + MissileWarfare 1.6.16
  + EssentialsSpawn 2.19.8-dev+2-b808511
  + SimpleStorage DEV - 10 (git ea5e5637)
  + GlobalWarming DEV - 11 (git 73ff77d4)
  + MiniBlocks DEV - 4 (git f7a34b6e)
  + SfChunkInfo DEV - 7 (git 30b6d0ef)
  + Bump Build 30 zh-CN(SlimefunGuguProject) (git 31e1bb3)
  + ExtraGear DEV - 13 (git c62047e2)
  + InteractiveChat 4.2.3.1
  + SFAdvancements DEV - 21 (git e6f6cf10)
  + SlimeHUD DEV - 7 (git fd655730)
  + SFCalc DEV - 37 (git dfc0fc41)
  + MobCapturer DEV - 21 (git f82c20fc)
  + Oneblock 1.0.7+
  + TranscEndence DEV - 41 (git 98d7d47e)
  + Shopkeepers 2.16.2
  + AlchimiaVitae DEV - 22 (git 09618c12)
  + HotbarPets DEV - 38 (git fa6c871d)
  + SlimefunLuckyBlocks DEV - 36 (git 60f0c8dc)
  + ExoticGarden DEV - 78 (git 7f9a5f63)
  + HeadLimiter DEV - 14 (git 0a02e2fd)
  + Liquid DEV - 14 (git 0f5346bf)
  + SFMobDrops DEV - 6 (git d36aba47)
  + SoulJars DEV - 23 (git b8358a1f)
  + GriefPrevention 16.18
  + PotionExpansion DEV - 5 (git e2cfcd8a)
  + Landlord 5.0.0-DEV+401699a
  + SlimyRepair DEV - 4 (git 790c41cb)
  + ExtraTools DEV - 36 (git 922c0324)
  + RelicsOfCthonia DEV - 6 (git 5ba8f971)
  + FoxyMachines DEV - 58 (git c2c2b8a7)
  + SlimefunOreChunks DEV - 15 (git 2520cb23)
  + StackMob 5.8.4
  + SimpleMaterialGenerators DEV - 4 (git 5543cc8f)
  + DyeBench DEV - 5 (git ea20db26)
  + Supreme DEV - 11 (git 448154ef)
  + ElectricSpawners DEV - 23 (git 6ec96773)
  + Wildernether DEV - 5 (git 5be3da69)
  + CompressionCraft DEV - 23 (git 8a50d1d6)
  + VillagerUtil DEV - 1 (git 0a949b19)
  + ExtraHeads DEV - 23 (git 0b59a770)
  + SlimyTreeTaps DEV - 20 (git 963f0383)
  + FlowerPower DEV - 15 (git 35662ced)
  + PrivateStorage DEV - 18 (git 5832db21)
  + Galactifun DEV - 70 (git c69305ef)
  + FluffyMachines DEV - 126 (git cc67cc03)
  + DyedBackpacks DEV - 17 (git 8b329e96)
  + SoundMuffler DEV - 24 (git ae8e2bf7)
  + LiteXpansion DEV - 181 (git 79885526)
  + FNAmplifications DEV - 79 (git 220e6eb2)
  + ElementManipulation DEV - 25 (git dffbefdc)
  + InfinityExpansion DEV - 140 (git 0098d2fb)
  + Networks DEV - 44 (git 2e7bc54c)
  + DynaTech DEV - 170 (git a5e7b101)
  + SimpleUtils DEV - 15 (git 4250fd5e)
  + SlimefunWarfare DEV - 81 (git a3f393c8)
  + SlimeTinker DEV - 77 (git 99a520b9)
  + CrystamaeHistoria DEV - 78 (git 340f1a94)
  + SlimeCustomizer DEV - 27 (git 3d8b02e5)
  + EMCTech DEV - 3 (git bdc78e46)

Block Info:
  World: world_nether
  X: 609
  Y: 61
  Z: 375
  Material: PLAYER_HEAD
  Block Data: org.bukkit.craftbukkit.v1_19_R1.block.impl.CraftSkullPlayer
  State: org.bukkit.craftbukkit.v1_19_R1.block.CraftSkull

Ticker-Info:
  Type: Synchronized

Slimefun Data:
  ID: NPS_SOUL_SEED
  Inventory: true
  Data: {"growth-stage":"6","id":"NPS_SOUL_SEED","plant-owner":"67c4b594-1851-3ffa-878b-51ccd2e8989f"}

Stacktrace:

java.lang.NullPointerException: Owner is null, has this been called correctly
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907)
	at Netheopoiesis - DEV 11 (git 57ce4).jar//dev.sefiraat.netheopoiesis.api.items.NetherSeed.getOwner(NetherSeed.java:266)
	at Netheopoiesis - DEV 11 (git 57ce4).jar//dev.sefiraat.netheopoiesis.api.items.CruxSpreadingSeed.spread(CruxSpreadingSeed.java:63)
	at Netheopoiesis - DEV 11 (git 57ce4).jar//dev.sefiraat.netheopoiesis.api.items.CruxSpreadingSeed.onTickFullyGrown(CruxSpreadingSeed.java:41)
	at Netheopoiesis - DEV 11 (git 57ce4).jar//dev.sefiraat.netheopoiesis.api.items.NetherSeed.onTick(NetherSeed.java:160)
	at Netheopoiesis - DEV 11 (git 57ce4).jar//dev.sefiraat.netheopoiesis.api.items.NetherSeed$1.tick(NetherSeed.java:130)
	at Slimefun4 - DEV 1027 (git 96c87).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:189)
	at Slimefun4 - DEV 1027 (git 96c87).jar//io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.lambda$tickLocation$2(TickerTask.java:170)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1493)
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1417)
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1193)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by J3fftw1** [comment]
Sorry for the late late reply, but after further checking (4 months later) it seems to be related to https://github.com/Slimefun/Slimefun4/issues/3696
